# Generated by Django 5.1.2 on 2025-01-13 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_alter_profile_otp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_with',
            field=models.EmailField(max_length=254),
        ),
    ]
