# Generated by Django 5.1.2 on 2025-01-24 15:58

import datetime
import uuid
from django.db import migrations, models

def generate_unique_tokens(apps, schema_editor):
    SharedFile = apps.get_model('myapp', 'SharedFile')
    for file in SharedFile.objects.all():
        file.share_token = str(uuid.uuid4())
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_remove_file_user_id_file_user_alter_file_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 15, 57, 32, 165703, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='share_token',
            field=models.CharField(
                default=uuid.uuid4, 
                max_length=255, 
                unique=True
                ),
        ),
        migrations.RunPython(generate_unique_tokens),

    ]


