# Generated by Django 5.1.2 on 2025-02-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
