# Generated by Django 5.1.2 on 2025-02-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_alter_sharedfile_allow_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='password',
            new_name='password_hash',
        ),
    ]
