# Generated by Django 5.1.2 on 2025-02-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_rename_password_sharedfile_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='has_been_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='one_time_view',
            field=models.BooleanField(default=False),
        ),
    ]
