# Generated by Django 5.1.2 on 2025-02-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_sharedfile_has_been_viewed_sharedfile_one_time_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
