# Generated by Django 5.1.2 on 2025-03-08 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_filefrequenly_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefrequenly',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
