# Generated by Django 5.1.2 on 2025-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_alter_filefrequenly_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefrequenly',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
