# Generated by Django 5.1.2 on 2025-03-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_alter_filefrequenly_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefrequenly',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
