# Generated by Django 5.1.2 on 2025-04-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0085_alter_filefrequenly_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_failed_otp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_locked',
            field=models.BooleanField(default=False),
        ),
    ]
